/* Generated By:JavaCC: Do not edit this line. XmlParserConstants.java */
//package parseurjava;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XmlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int OPEN_TAG = 2;
  /** RegularExpression Id. */
  int CLOSE_TAG = 3;
  /** RegularExpression Id. */
  int SLASH = 4;
  /** RegularExpression Id. */
  int EQUAL = 5;
  /** RegularExpression Id. */
  int QUOTE = 6;
  /** RegularExpression Id. */
  int TEXT = 7;
  /** RegularExpression Id. */
  int NAME = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"<\"",
    "\">\"",
    "\"/\"",
    "\"=\"",
    "\"\\\"\"",
    "<TEXT>",
    "<NAME>",
  };

}
